package com.skids.idamobile.decompiler

/**
 * End-to-end decompilation report generated by local radare2 execution.
 */
data class Radare2DecompileReport(
    val dexPath: String,
    val abi: String,
    val functionCount: Int,
    val wasTruncated: Boolean,
    val functions: List<Radare2Function>,
    val selectedFunction: Radare2Function?,
    val pseudoCode: String
)
