#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
R2_DIR="${ROOT_DIR}/third_party/radare2"
ASSET_ROOT="${ROOT_DIR}/app/src/main/assets/tools/radare2"
TARGET_ABI="${1:-arm64-v8a}"

if [[ ! -d "${R2_DIR}" ]]; then
  echo "Missing ${R2_DIR}. Run scripts/setup_third_party.ps1 first."
  exit 1
fi

case "${TARGET_ABI}" in
  arm64-v8a)
    BUILD_TARGET="arm64-static"
    ;;
  armeabi-v7a)
    BUILD_TARGET="arm-static"
    ;;
  *)
    echo "Unsupported ABI: ${TARGET_ABI}. Supported: arm64-v8a, armeabi-v7a"
    exit 1
    ;;
esac

if [[ -z "${NDK:-}" && -n "${ANDROID_NDK_HOME:-}" ]]; then
  export NDK="${ANDROID_NDK_HOME}"
fi

if [[ -z "${NDK:-}" ]]; then
  echo "Set NDK or ANDROID_NDK_HOME before running this script."
  exit 1
fi

cd "${R2_DIR}"
sys/android-shell.sh sys/android-build.sh "${BUILD_TARGET}"

# Locate built r2 binary in packaged output generated by android-build.sh.
R2_BIN_PATH="$(find "${R2_DIR}" -type f -path "*/data/data/org.radare.radare2installer/radare2/bin/r2" | head -n 1)"

if [[ -z "${R2_BIN_PATH}" ]]; then
  echo "Could not locate built r2 binary."
  exit 1
fi

DEST_DIR="${ASSET_ROOT}/${TARGET_ABI}"
mkdir -p "${DEST_DIR}"
cp "${R2_BIN_PATH}" "${DEST_DIR}/r2"
chmod +x "${DEST_DIR}/r2"

echo "Installed radare2 binary to ${DEST_DIR}/r2"
